#!/bin/bash
count=1
sum=0
a=$1
while [ $count -le $a ]
do
echo "$count,`date '+%Y%m%d%H%M%S'`" >> $count.txt
sum=$(expr `cat $count.txt | awk -F "," '{print$1}'` + $sum)
count=`expr $count + 1`
done
echo "total will be: $sum"
